//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baskets
    {
        public int Id { get; set; }
        public Nullable<int> Car { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
