//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Status { get; set; }
        public byte[] PhotoUser { get; set; }

        public string UserGender { get; set; }
        public string UserRole { get; set; }
        public string UserStatus { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
